IF OBJECT_ID('dbo.SUSCRIPTORES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.SUSCRIPTORES (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    correo NVARCHAR(255) NOT NULL UNIQUE,
    fecha_suscripcion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    activo BIT NOT NULL DEFAULT 1
  );
END;
GO

IF OBJECT_ID('dbo.SUSCRIPTORES_NOTIFICACIONES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.SUSCRIPTORES_NOTIFICACIONES (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    tipo NVARCHAR(80) NOT NULL,
    titulo NVARCHAR(255) NOT NULL,
    enviados INT NOT NULL DEFAULT 0,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO
